name: Deploy Gemini Video Analyzer

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      prompt:
        description: '分析提示词'
        required: true
        default: '请分析这个视频的主要内容'
      youtube_url:
        description: 'YouTube视频链接'
        required: true
        default: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'
      webhook_url:
        description: 'Webhook地址（可选）'
        required: false
        default: ''

jobs:
  analyze-video:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Video Analysis
      env:
        GOOGLE_AI_API_KEY: ${{ secrets.GOOGLE_AI_API_KEY }}
      run: |
        if [ -n "${{ github.event.inputs.webhook_url }}" ]; then
          python cli_analyzer.py \
            --prompt "${{ github.event.inputs.prompt }}" \
            --youtube "${{ github.event.inputs.youtube_url }}" \
            --webhook "${{ github.event.inputs.webhook_url }}"
        else
          python cli_analyzer.py \
            --prompt "${{ github.event.inputs.prompt }}" \
            --youtube "${{ github.event.inputs.youtube_url }}"
        fi